name: hive

services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      - PHP_MYSQL_HOSTNAME=${PHP_MYSQL_HOSTNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8000:8000
    restart: unless-stopped
