name: hive

services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: app.dockerfile
    depends_on:
      - mysql
    environment:
      - PHP_MYSQL_HOSTNAME=${PHP_MYSQL_HOSTNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - AI_BASE_URI=${AI_BASE_URI}
    ports:
      - 8000:8000
    restart: unless-stopped

  ai:
    build:
      context: .
      dockerfile: ai.dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
