name: hive

services:
  mysql:
    image: mysql:8.3
    container_name: hive_mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: hive_php
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: unless-stopped
